#pragma once
class RootNode;
class JaggedArrayNode;
class SimpleArrayNode;
class classDefNode;
class funcDefNode;
class varDefNode;
class assignExprNode;
class atomExprNode;
class binaryExprNode;
class formatStringExprNode;
class functionCallExprNode;
class classMemExprNode;
class SubscriptExprNode;
class TenaryExprNode;
class UnaryExprNode;
class LiteralPrimaryNode;
class NewPrimaryNode;
class ThisPrimaryNode;
class VarPrimaryNode;
class controlStmtNode;
class exprStmtNode;
class emptyStmtNode;
class forStmtNode;
class ifStmtNode;
class suiteStmtNode;
class varDefStmtNode;
class whileStmtNode;
class constructorClassStmtNode;
class functionDefClassStmtNode;
class varDefClassStmtNode;

class ASTVisitor {
  public:
  virtual void visit(RootNode *node) = 0;
  virtual void visit(JaggedArrayNode *node) = 0;
  virtual void visit(SimpleArrayNode *node) = 0;
  virtual void visit(classDefNode *node) = 0;
  virtual void visit(funcDefNode *node) = 0;
  virtual void visit(varDefNode *node) = 0;
  virtual void visit(assignExprNode *node) = 0;
  virtual void visit(atomExprNode *node) = 0;
  virtual void visit(binaryExprNode *node) = 0;
  virtual void visit(formatStringExprNode *node) = 0;
  virtual void visit(functionCallExprNode *node) = 0;
  virtual void visit(classMemExprNode *node) = 0;
  virtual void visit(SubscriptExprNode *node) = 0;
  virtual void visit(TenaryExprNode *node) = 0;
  virtual void visit(UnaryExprNode *node) = 0;
  virtual void visit(LiteralPrimaryNode *node) = 0;
  virtual void visit(NewPrimaryNode *node) = 0;
  virtual void visit(ThisPrimaryNode *node) = 0;
  virtual void visit(VarPrimaryNode *node) = 0;
  virtual void visit(controlStmtNode *node) = 0;
  virtual void visit(exprStmtNode *node) = 0;
  virtual void visit(emptyStmtNode *node) = 0;
  virtual void visit(forStmtNode *node) = 0;
  virtual void visit(ifStmtNode *node) = 0;
  virtual void visit(suiteStmtNode *node) = 0;
  virtual void visit(varDefStmtNode *node) = 0;
  virtual void visit(whileStmtNode *node) = 0;
  virtual void visit(constructorClassStmtNode *node) = 0;
  virtual void visit(functionDefClassStmtNode *node) = 0;
  virtual void visit(varDefClassStmtNode *node) = 0;
};